### ISSUE TITLE
Long-term Statistics

### ISSUE THREAD

**Issue by totalitarian** [timmo001/ovoenergy#26]
I would like to use this with the new energy dashboard but in order for it to work I think we need to setup the sensors to support statistics and noted below?

Home Assistant has support for storing sensors as long-term statistics if the entity has the right properties. A requirement to opt-in for statistics is that the sensor has state_class set to measurement. That means that the current value represents the current value.

**Comment by timmo001** [comment]
Done in https://github.com/home-assistant/core/pull/54157

**Comment by totalitarian** [comment]
Wow that was quick. Many thanks.

**Comment by timmo001** [comment]
It's been on my todo list 😉
