### ISSUE TITLE
Requirement is pinned for ovoenergy 1.1.7: aiohttp==3.6.2

### ISSUE THREAD

**Issue by MartinHjelmare** [timmo001/ovoenergy#7]
# Description
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

## How to reproduce the issue (if applicable)
```
(home-assistant) x$ pip install -r requirements_all.txt
...
(home-assistant) x$ pipdeptree -w silence -r -p aiohttp | grep ovoenergy
  - ovoenergy==1.1.7 [requires: aiohttp==3.6.2]
```

**Comment by timmo001** [comment]
Unpinned and updated packages. Update incoming :ship:
