### ISSUE TITLE
'Invalid authentication'

### ISSUE THREAD

**Issue by wayneconnor** [timmo001/ovoenergy#76]
### Description

I'm getting 'Invalid authentication' when I try to add the integration.
I've reset my OVO password so I'm sure it's right.
Anyone else had this problem?
Is this  integration working currently?
Thanks,
Wayne

### What Platform / OS are you running?

Mac OS

### What version are you running?

latest 30 sept from HA

**Comment by timmo001** [comment]
There has been a recent refactor which updates to the newest authentication method that OVO use. I will be deploying this package soon and updating home assistant's integration
