### ISSUE TITLE
Dev Input required - OVO API rule changes

### ISSUE THREAD

**Issue by blastoise186** [timmo001/ovoenergy#80]
### Description

Hi,

Posting this as one of the OVO Forum Volunteers, I don't work for OVO myself.

OVO has announced some rule changes that you may need to be aware of. Please see https://forum.ovoenergy.com/my-account-140/can-we-get-access-to-the-ovo-energy-online-account-api-to-download-our-smart-meter-usage-data-58?postid=116315#post116315 as it may be relevant to you.

You may need to make changes in response to this and may want to contribute to the discussion over there.

### What Platform / OS are you running?

Linux

### What version are you running?

1.3.1

**Comment by timmo001** [comment]
Thanks for the info. Hopefully they wont see much issue of this package as it emulates the same calls the portal does (actually less since there is no need for some data).
